//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitch_Bot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twitch_Bot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8wnkl2nkns3p4wrkq49vidpfc0pixj.
        /// </summary>
        internal static string bot_access_token {
            get {
                return ResourceManager.GetString("bot_access_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheSpeakerBot.
        /// </summary>
        internal static string bot_name {
            get {
                return ResourceManager.GetString("bot_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uhv8e7qbr63fdustsm61u9ow9dcsokksugv8bllb2pqgon6rdy.
        /// </summary>
        internal static string bot_refresh_token {
            get {
                return ResourceManager.GetString("bot_refresh_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItsLittany.
        /// </summary>
        internal static string channel_name {
            get {
                return ResourceManager.GetString("channel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h80f0u9f86934pniin2xq82lc252fj.
        /// </summary>
        internal static string client_id {
            get {
                return ResourceManager.GetString("client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k1d5k9yuruwguolegg6bcqjzqp8baz.
        /// </summary>
        internal static string client_secret {
            get {
                return ResourceManager.GetString("client_secret", resourceCulture);
            }
        }
    }
}
